### PR TITLE
Add getters for scale and offset

### PR DESCRIPTION
**Pull request by dimastark**
We use scale and offset meta data to pack float into an integer type. Therefore, I would really like to merge this pull request.

### CODE REVIEW

**Comment by tbonfort** [comment]
I'm thinking that the scale and offset would be better off surfacing inside Band.Structure(), for easier access and less cgo calls

**Comment by tbonfort** [comment]
@dimastark do you have any plans to implement setters also?

**Comment by dimastark** [comment]
Ok, I'll try to implement it, but I'm not sure if I can

**Comment by tbonfort** [comment]
> Ok, I'll try to implement it, but I'm not sure if I can

thank you for the setters. sorry for nitpicking, but in another effort to reduce cgo calls, could you please use only a single function to set scale and offset in a single call as both usually go together. For the tests I also believe that we can avoid adding a static test tif, and use a MEM driver to cover the setters and the getters.

**Comment by tbonfort** [comment]
thanks @dimastark

**Pull request merged**
